<?php
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
require dirname(__DIR__,4).'/wp-load.php';
use Calendly_Bookings\Modules\CB_API;
use Calendly_Bookings\Modules\CB_Checkout;
use Calendly_Bookings\Modules\CB_Frontend;
use Calendly_Bookings\Modules\CB_Booking_Reconciliation as Worker;
use Calendly_Bookings\Modules\CB_Email;
$passed=0;function test($ok,$label){global $passed;if(!$ok)throw new RuntimeException('FAIL: '.$label);$passed++;echo 'PASS: '.$label.PHP_EOL;}
$type=$wpdb->get_row("SELECT uuid,product_id FROM {$wpdb->prefix}cb_event_types WHERE active=1 AND product_id>0 LIMIT 1",ARRAY_A);
if(!$type)throw new RuntimeException('No mapped meeting product for fixture.');
$product=wc_get_product($type['product_id']);$uuid=(string)$product->get_meta('_cb_event_uuid',true);if(!$uuid)$uuid=$type['uuid'];
$definition=['uri'=>'https://api.calendly.com/event_types/'.$uuid,'locations'=>[['kind'=>'zoom_conference','extra_host_metadata'=>'not sent'],['kind'=>'outbound_call']],'custom_questions'=>[['name'=>' Tell us about your goals. ','position'=>0,'enabled'=>true,'required'=>true,'type'=>'text'],['name'=>'Practices','position'=>1,'enabled'=>true,'required'=>true,'type'=>'multi_select']]];
$key1=CB_Frontend::question_key($definition['custom_questions'][0]);$key2=CB_Frontend::question_key($definition['custom_questions'][1]);
$text="First line: café & wellbeing 🌿\nC:\\notes\\goals — O'Connor";$start=gmdate('Y-m-d\TH:i:s\Z',time()+86400*10);
$cachekey='cb_event_definition_'.md5($uuid);$oldcache=get_transient($cachekey);set_transient($cachekey,$definition,300);
$oldpost=$_POST;$instance=new ReflectionProperty(CB_API::class,'instance');$oldinstance=$instance->getValue();$token='booking-flow-fixture';$instance->setValue(null,new CB_API($token,'fixture-user'));
$calls=[];$postcalls=[];$invalid=false;$mail=[];$urls=[];
$http=function($pre,$args,$url)use(&$calls,&$postcalls,&$invalid,&$urls,$definition){
 if(!str_starts_with($url,'https://api.calendly.com/'))return new WP_Error('fixture_network_blocked','External network blocked during booking test.');
 $urls[]=$url;$calls[]=$url;$status=200;$body=['resource'=>$definition];
 if(($args['method']??'GET')==='POST'){$payload=json_decode($args['body'],true);$postcalls[]=$payload;$status=$invalid?400:201;$body=$invalid?['message'=>'The supplied parameters are invalid.','details'=>[['parameter'=>'questions_and_answers','message'=>'fixture parameter error']]]:['resource'=>['uri'=>'https://api.calendly.com/scheduled_events/12345678-1234-1234-1234-123456789abc/invitees/87654321-4321-4321-4321-123456789abc','event'=>'https://api.calendly.com/scheduled_events/12345678-1234-1234-1234-123456789abc','cancel_url'=>'https://calendly.com/cancellations/fixture','reschedule_url'=>'https://calendly.com/reschedulings/fixture','questions_and_answers'=>$payload['questions_and_answers'],'email'=>$payload['invitee']['email']]];}
 return ['headers'=>[],'body'=>wp_json_encode($body),'response'=>['code'=>$status,'message'=>'fixture'],'cookies'=>[]];};
$blockmail=function($pre,$atts)use(&$mail){$mail[]=$atts;return true;};add_filter('pre_http_request',$http,1,3);add_filter('pre_wp_mail',$blockmail,1,2);
$order=null;
try{
 $_POST=wp_slash(['cb_event_uuid'=>$uuid,'cb_event_type_uri'=>$definition['uri'],'cb_meeting_start_iso'=>$start,'cb_meeting_date'=>'2030-01-01','cb_meeting_time'=>$start,'cb_meeting_location'=>CB_Frontend::location_key($definition['locations'][0],0),'cb_calendly_answers'=>[$key1=>$text,$key2=>['Meditation','Other']],'cb_calendly_answers_other'=>[$key2=>'Breath work'],'cb_prep_notes'=>$text,'order_comments'=>$text]);
 $cart=CB_Checkout::capture_form_data([],$product->get_id(),0);
 test($cart['cb_calendly_answers'][$key1]===$text,'Product capture preserves Unicode, multiline text, quotes and backslashes');test($cart['cb_question_labels'][$key1]==='Tell us about your goals.','Server-owned question labels are captured');test($cart['cb_meeting_location_label']==='Zoom Conference','Server-owned location label is captured');
 $order=new WC_Order();$order->set_billing_first_name('Zoë');$order->set_billing_last_name("O'Connor");$order->set_billing_email('booking-fixture@example.invalid');$order->set_total(0);
 $item=new WC_Order_Item_Product();$item->set_product($product);$item->set_quantity(1);$item->set_subtotal(0);$item->set_total(0);CB_Checkout::save_booking_item_meta($item,'fixture',$cart,$order);$order->add_item($item);
 $_POST=[];CB_Checkout::save_order_meta($order,[]);
 test($order->get_meta('_cb_prep_notes',true)===$text && $order->get_meta('_cb_meeting_notes',true)===$text,'Checkout does not unslash persisted cart text a second time');test(json_decode($order->get_meta('_cb_calendly_answers',true),true)[$key1]===$text,'Order answers survive JSON persistence');test(json_decode($item->get_meta('_cb_booking_answers',true),true)[$key2]===['Meditation','Other'],'Multiselect values survive line-item persistence');
 $html=CB_Checkout::render_meeting_details($order);$plain=CB_Checkout::render_meeting_details($order,true);test(str_contains($html,'Tell us about your goals.') && !str_contains($html,$key1),'HTML order details use question labels');test(str_contains($html,'&amp;') && str_contains($html,'<br') && str_contains($html,'C:\\notes\\goals'),'HTML preserves readability and escapes values');test(str_contains($plain,$text) && !str_contains($plain,'<table'),'Plain-text details preserve original line breaks');test(str_contains($plain,'Meditation')&&str_contains($plain,'Other: Breath work'),'Multiselect and Other answers remain readable');test(str_contains($plain,'America/Barbados'),'Meeting time shows its timezone');
 $cartdisplay=CB_Checkout::display_cart_item_data([],$cart);test(count(array_filter($cartdisplay,fn($row)=>($row['key']??'')==='Tell us about your goals.'))===1,'Cart shows dynamic question labels');
 $payloadmethod=new ReflectionMethod(Worker::class,'build_payload');$payload=$payloadmethod->invoke(null,$order,$definition,$uuid,$start,'Zoë',"O'Connor",'booking-fixture@example.invalid');test($payload['questions_and_answers'][0]['question']===$definition['custom_questions'][0]['name'],'Scheduling question text exactly matches Calendly including whitespace');test($payload['questions_and_answers'][0]['answer']===$text,'Scheduling answer preserves complete multiline Unicode value');test($payload['location']===['kind'=>'zoom_conference'],'Scheduling location excludes host-only metadata');test($payload['start_time']===$start,'Exact selected UTC slot is retained');test(array_key_exists('utm_term',$payload['tracking']) && array_key_exists('salesforce_uuid',$payload['tracking']) && $payload['tracking']['utm_term']===null && $payload['tracking']['salesforce_uuid']===null,'Scheduling tracking includes unused nullable fields');
 $order->save();$order=wc_get_order($order->get_id());Worker::process_order($order->get_id());$order=wc_get_order($order->get_id());
 test(count($postcalls)===1 && $postcalls[0]['questions_and_answers'][0]['answer']===$text,'Worker posts the complete saved form to POST /invitees');test($postcalls[0]['tracking']['utm_content']===(string)$order->get_id(),'Tracking uses the real order ID for webhook reconciliation');test((int)$order->get_meta('_cb_calendly_create_http_status',true)===201,'Order captures Scheduling API HTTP 201');test(!empty(json_decode($order->get_meta('_cb_calendly_create_response_body',true),true)['resource']['uri']),'Order captures successful response body');test($order->get_meta('_cb_calendly_booking_status',true)==='awaiting_webhook','Creation waits for verified webhook confirmation');Worker::process_order($order->get_id());test(count($postcalls)===1,'Awaiting-webhook booking is not submitted again');
 ob_start();CB_Checkout::add_to_emails($order,false,true,null);$emailplain=ob_get_clean();test(str_contains($emailplain,$text),'WooCommerce plain-text email contains form answers');ob_start();CB_Checkout::add_to_emails($order,false,false,null);$emailhtml=ob_get_clean();test(str_contains($emailhtml,'Tell us about your goals.')&&str_contains($emailhtml,'<br'),'WooCommerce HTML email contains readable form answers');
 CB_Email::send_booking_email($order,CB_Email::TEMPLATE_CONFIRMED);test(count($mail)===1&&str_contains($mail[0]['message'],'Tell us about your goals.'),'Calendly custom confirmation email includes form details without sending mail');
 $order->update_meta_data('_cb_calendly_booking_status','failed');$order->save();$invalid=true;Worker::process_order($order->get_id());$order=wc_get_order($order->get_id());test((int)$order->get_meta('_cb_calendly_create_http_status',true)===400,'Failed Scheduling API status is captured');test(str_contains($order->get_meta('_cb_calendly_create_response_body',true),'fixture parameter error'),'Failed API body is captured');test(str_contains($order->get_meta('_cb_calendly_booking_error',true),'questions_and_answers'),'Parameter error details reach order diagnostics');
 $locationmethod=new ReflectionMethod(Worker::class,'resolve_location');$order->update_meta_data('_cb_meeting_location',CB_Frontend::location_key($definition['locations'][1],1));$order->update_meta_data('_cb_meeting_location_detail_text','+12465550123');test($locationmethod->invoke(null,$order,$definition)===['kind'=>'outbound_call','location'=>'+12465550123'],'Invitee phone location reaches Scheduling API');$round=$definition;$round['pooling_type']='round_robin';test($locationmethod->invoke(null,$order,$round)===null,'Round-robin Scheduling API omits location');$order->update_meta_data('_cb_meeting_location_detail_text','');$throws=false;try{$locationmethod->invoke(null,$order,$definition);}catch(RuntimeException $e){$throws=true;}test($throws,'Missing required location input stops the request');
 echo $passed.' booking-flow checks passed.'.PHP_EOL;
}finally{
 remove_filter('pre_http_request',$http,1);remove_filter('pre_wp_mail',$blockmail,1);$_POST=$oldpost;$instance->setValue(null,$oldinstance);
 if($oldcache===false)delete_transient($cachekey);else set_transient($cachekey,$oldcache,300);
 foreach(array_unique($urls)as$url)delete_transient('cb_api_'.md5($token.'|'.$url));
 if($order && $order->get_id()){if(function_exists('as_unschedule_all_actions'))as_unschedule_all_actions(Worker::ACTION_HOOK,['order_id'=>$order->get_id()],'calendly-bookings');wp_clear_scheduled_hook('cb_booking_process_order_fallback',[$order->get_id()]);$order->delete(true);}
}
